CREATE OR REPLACE FUNCTION UpdateMwhenGretired()
RETURNS TRIGGER AS $$
BEGIN
			UPDATE Militanza
			SET Data_Fine = CURRENT_DATE
			WHERE SSN = NEW.SSN AND Data_Fine IS NULL; 
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER UpdateMwhenGretired
AFTER UPDATE ON Giocatore
FOR EACH ROW
WHEN (NEW.Ritirato)
EXECUTE FUNCTION UpdateMwhenGretired();
